### ISSUE TITLE
Video player throws onChange handler error in React 18 Vite

### ISSUE THREAD

**Issue by snivets** [react95-io/React95#389]
Hey - new to React. Trying to use the `Video` component exactly as is used in Storybook in a new React 18 Vite project, and run across this error: `Warning: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.`. What is going on under the hood here?

The code is the following:
<Video w="320" src="https://media.w3.org/2010/05/sintel/trailer_hd.mp4"  style={{
          marginBottom: 4
        }} />

**Comment by arturbien** [comment]
@snivets I think you were suppose to submit the issue here: https://github.com/React95/React95

There's two React95 libraries and ours doesn't have the Video component 🤓

**Comment by snivets** [comment]
Dangit, silly me. Thanks for the friendly correction. Why *are* there two libraries btw, is there a feud? :joy:
In case anyone ever arrives here from Google: https://github.com/React95/React95/issues/409
